version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 # _plus 0.0.0.0:8000 --cert-file cert.crt
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8000:8000
    env_file:
      - docker/dev/env/.env
      - docker/accounts.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/db.env
  redis:
    image: redis:6.0.1-alpine
    restart: always


volumes:
  postgres_data:
