version: '3.7'

services:
  web:
    build: ./Django-layout
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Django-layout/:/usr/src/Django-layout/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data: