version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    entrypoint: /entrypoint.sh
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - 8000:8000
    env_file:
      - docker/dev/env/.env
      - docker/.env.accounts
    depends_on:
      - db
    restart: always
  db:
    image: postgres:12.0-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/db.env
  redis:
    image: redis:6.0.1-alpine
    restart: always
  celery:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: celery -A src worker -l info
    volumes:
      - ./web/:/usr/src/web/
    env_file:
      - docker/dev/env/.env
    depends_on:
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: celery -A src beat -l info
    volumes:
      - ./web/:/usr/src/web/
    env_file:
      - docker/dev/env/.env
    depends_on:
      - redis

  jupyter_notebook:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py shell_plus --notebook
    depends_on:
      - web
    ports:
    - 8888:8888
    env_file:
      - docker/dev/env/.env
volumes:
  postgres_data:
