version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: docker/prod/web/Dockerfile
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./web/:/home/www/web/
      - static_volume:/home/www/web/static
      - media_volume:/home/www/web/media
    expose:
      - 8000
    env_file:
      - docker/prod/env/.env
      - docker/accounts.env
    depends_on:
      - db
      - redis
    restart: unless-stopped
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/prod/env/db.env
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: docker/prod/nginx/Dockerfile
    volumes:
      - static_volume:/home/www/web/static
      - media_volume:/home/www/web/media
    ports:
      - 80:80
    depends_on:
      - web
    restart: unless-stopped
  redis:
    image: redis:6.0.1-alpine
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:

